# Generated by Django 6.0.6 on 2026-07-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_imageupload_arquivo'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='images.imageupload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(max_length=100),
        ),
    ]
