# Generated by Django 6.0.6 on 2026-07-15 04:25

import images.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='arquivo',
            field=models.ImageField(upload_to='uploads/', validators=[images.validators.validar_imagem, images.validators.validar_tipo_arquivo]),
        ),
    ]
